# Generated by Django 4.0.6 on 2022-07-13 15:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Showroom Name')),
                ('description', models.TextField(blank=True, help_text='<i>More information about your company...</i>')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('start_year', models.DateField(default=2022)),
                ('balance', models.PositiveIntegerField(default=1000000, help_text='<i>Put your balance in dollars</i>', verbose_name='Balance')),
                ('price_increase', models.PositiveSmallIntegerField(default=30, help_text='<b>Enter the markup on the cars you sell</b>', validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cars_options', models.JSONField(verbose_name='Car priority')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
            },
        ),
        migrations.CreateModel(
            name='ShowroomDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='How many cars do I need to buy for the discount?', validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.PositiveIntegerField(default=1, help_text='Enter the size of the discount in percent', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('data_start', models.DateField()),
                ('data_end', models.DateField(default=datetime.date(2022, 8, 12))),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='DealerShowroomDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showroom.showroom')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealer.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealer.dealer')),
            ],
            options={
                'verbose_name': 'Dealer --> Showroom deal',
                'verbose_name_plural': 'Dealer --> Showroom deals',
            },
        ),
    ]
