# Generated by Django 4.0.6 on 2022-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_showroomdiscount_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='cars_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Car priority'),
        ),
    ]
