# Generated by Django 4.0.6 on 2022-07-25 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_showroom_cars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomdiscount',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 8, 24)),
        ),
        migrations.AlterField(
            model_name='showroomdiscount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='showroom.showroom'),
        ),
    ]
