# Generated by Django 4.0.6 on 2022-07-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('username', models.CharField(help_text='<i>Put your unique username</i>', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('balance', models.PositiveIntegerField(default=100000, help_text='<i>Put your balance in dollars</i>', verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomCustomerDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealer.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showroom.showroom')),
            ],
            options={
                'verbose_name': 'Showroom  --> Customer deal',
                'verbose_name_plural': 'Showroom  --> Customer deals',
            },
        ),
    ]
