# Generated by Django 4.0.6 on 2022-07-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.PositiveIntegerField(default=0, help_text='<i>Put your balance in dollars</i>', verbose_name='Balance')),
                ('cars_options', models.JSONField(blank=True, null=True, verbose_name='Car priority')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('username', models.CharField(help_text='<i>Put your unique username</i>', max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
