# Generated by Django 4.1 on 2022-08-16 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomdiscountscars',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
    ]
