# Generated by Django 4.0.6 on 2022-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_showroom_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
