# Generated by Django 4.0.6 on 2022-07-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('showroom', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomCustomerDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to='customer.customer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_info', to='dealer.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='showroom.showroom')),
            ],
            options={
                'verbose_name': 'Showroom  --> Customer deal',
                'verbose_name_plural': 'Showroom  --> Customer deals',
            },
        ),
        migrations.CreateModel(
            name='DealerShowroomDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to='showroom.showroom')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealer.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='dealer.dealer')),
            ],
            options={
                'verbose_name': 'Dealer --> Showroom deal',
                'verbose_name_plural': 'Dealer --> Showroom deals',
            },
        ),
    ]
