# Generated by Django 4.1 on 2022-08-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('dealer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomCustomerDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_info', to='car.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='showroom.showroom')),
            ],
            options={
                'verbose_name': 'Showroom  --> Customer deal',
                'verbose_name_plural': 'Showroom  --> Customer deals',
            },
        ),
        migrations.CreateModel(
            name='DealerShowroomDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to='showroom.showroom')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='dealer.dealer')),
            ],
            options={
                'verbose_name': 'Dealer --> Showroom deal',
                'verbose_name_plural': 'Dealer --> Showroom deals',
            },
        ),
    ]
