# Generated by Django 4.0.6 on 2022-07-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cars_options'),
        ('showroom', '0003_alter_showroom_cars_options'),
        ('dealer', '0003_alter_car_dealer_alter_dealerdiscount_organization'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershowroomdeals',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to='showroom.showroom'),
        ),
        migrations.AlterField(
            model_name='dealershowroomdeals',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='showroomcustomerdeals',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_history', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='showroomcustomerdeals',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='showroom.showroom'),
        ),
    ]
