# Generated by Django 4.0.6 on 2022-07-25 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_showroomcustomerdeals_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershowroomdeals',
            name='deal_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
