# Generated by Django 4.0.6 on 2022-07-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
        migrations.AlterField(
            model_name='dealerdiscount',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 8, 21)),
        ),
    ]
