# Generated by Django 4.0.6 on 2022-07-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.IntegerField(choices=[(None, "Select car's color"), (1, 'Red'), (2, 'Grey'), (3, 'Light blue'), (4, 'Dark blue'), (5, 'Green'), (6, 'Yellow'), (7, 'Pink'), (8, 'Orange'), (9, 'Brown'), (10, 'White'), (11, 'Black'), (12, 'Violet')], verbose_name='Color'),
        ),
    ]
