# Generated by Django 4.0.6 on 2022-07-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_remove_car_is_active_remove_car_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_cars', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='dealerdiscount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='dealer.dealer'),
        ),
    ]
