# Generated by Django 4.0.6 on 2022-07-20 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_dealerdiscount_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdiscount',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 8, 19)),
        ),
    ]
