# Generated by Django 4.0.6 on 2022-07-25 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_car_dealer_alter_dealerdiscount_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[(None, "Select car's color"), ('Red', 'Red'), ('Grey', 'Grey'), ('Light blue', 'Light blue'), ('Dark blue', 'Dark blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Brown', 'Brown'), ('White', 'White'), ('Black', 'Black'), ('Violet', 'Violet')], max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='dealerdiscount',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 8, 24)),
        ),
    ]
