import random

cars_models = {
    "Aston Martin": [
        "Bulldog",
        "Cygnet",
        "DB AR1",
        "DB11",
        "DB5",
        "DB7",
        "DB9",
        "DBS",
        "DBX",
        "Lagonda",
        "One-77",
        "Rapide",
        "Tickford Capri",
        "V12 Vantage",
        "V12 Zagato",
        "V8 Vantage",
        "V8 Zagato",
        "Vanquish",
        "Virage",
        "Vulcan"
    ],
    "Audi": ["100",
             "200",
             "50",
             "80",
             "90",
             "920",
             "A1",
             "A2",
             "A3",
             "A4",
             "A4 allroad",
             "A5",
             "A6",
             "A6 allroad",
             "A7",
             "A8",
             "Cabriolet",
             "Coupe",
             "e-tron",
             "e-tron GT",
             "e-tron S",
             "e-tron S Sportback",
             "e-tron Sportback",
             "NSU RO 80",
             "Q2",
             "Q2L",
             "Q3",
             "Q3 Sportback",
             "Q4 e-tron",
             "Q4 Sportback e-tron",
             "Q5",
             "Q5 Sportback",
             "Q7",
             "Q8",
             "Quattro",
             "R8",
             "R8 LMP",
             "RS 2",
             "RS 3",
             "RS 4",
             "RS 5",
             "RS 6",
             "RS 7",
             "RS e-tron GT",
             "RS Q3",
             "RS Q3 Sportback",
             "RS Q8",
             "S1",
             "S2",
             "S3",
             "S4",
             "S5",
             "S6",
             "S7",
             "S8",
             "SQ2",
             "SQ5",
             "SQ5 Sportback",
             "SQ7",
             "SQ8",
             "TT",
             "TT RS",
             "TTS",
             "Typ R",
             "V8"
             ],
    "Bentley": [
        "Arnage",
        "Azure",
        "Bentayga",
        "Brooklands",
        "Continental",
        "Continental Flying Spur",
        "Continental GT",
        "Eight",
        "Flying Spur",
        "Mark VI",
        "Mulsanne",
        "R Type",
        "S",
        "T-Series",
        "Turbo R"
    ],
    "BMW": [
        "02 (E10)",
        "1 серии",
        "1M",
        "2 серии",
        "2 серии Active Tourer",
        "2 серии Gran Tourer",
        "2000 C/CS",
        "3 серии",
        "3/15",
        "315",
        "3200",
        "321",
        "326",
        "327",
        "340",
        "4 серии",
        "5 серии",
        "501",
        "502",
        "503",
        "507",
        "6 серии",
        "600",
        "7 серии",
        "700",
        "8 серии",
        "E3",
        "E9",
        "i3",
        "i4",
        "i7",
        "i8",
        "iX",
        "iX1",
        "iX3",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M8",
        "New Class",
        "X1",
        "X2",
        "X3",
        "X3 M",
        "X4",
        "X4 M",
        "X5",
        "X5 M",
        "X6",
        "X6 M",
        "X7",
        "Z1",
        "Z3",
        "Z3 M",
        "Z4",
        "Z4 M",
        "Z8"
    ],
    "Cadillac": [
        "Allante",
        "ATS",
        "ATS-V",
        "BLS",
        "Brougham",
        "Catera",
        "CT4",
        "CT4-V",
        "CT5",
        "CT5-V",
        "CT6",
        "CTS",
        "CTS-V",
        "DeVille",
        "DTS",
        "Eldorado",
        "ELR",
        "Escalade",
        "Fleetwood",
        "LSE",
        "Lyriq",
        "Series 62",
        "Seville",
        "Sixty Special",
        "SRX",
        "STS",
        "XLR",
        "XT4",
        "XT5",
        "XT6",
        "XTS"
    ],
    "Chevrolet": [
        "3000-Series",
        "Alero",
        "Apache",
        "Astra",
        "Astro",
        "Avalanche",
        "Aveo",
        "Bel Air",
        "Beretta",
        "Blazer",
        "Blazer K5",
        "Bolt",
        "Bolt EUV",
        "C-10",
        "C/K",
        "Camaro",
        "Caprice",
        "Captiva",
        "Captiva Sport",
        "Cavalier",
        "Celebrity",
        "Celta",
        "Chevelle",
        "Chevette",
        "Citation",
        "Cobalt",
        "Colorado",
        "Corsa",
        "Corsica",
        "Corvair",
        "Corvette",
        "Cruze",
        "Cruze (HR)",
        "CSV CR8",
        "Damas",
        "Deluxe",
        "El Camino",
        "Epica",
        "Equinox",
        "Evanda",
        "Express",
        "Fleetmaster",
        "HHR",
        "Impala",
        "Kalos",
        "Lacetti",
        "Lanos",
        "Lumina",
        "Lumina APV",
        "LUV D-MAX",
        "Malibu",
        "Master",
        "Matiz",
        "Metro",
        "Monte Carlo",
        "Monza",
        "MW",
        "Nexia",
        "Niva",
        "Nova",
        "Nubira",
        "Omega",
        "Orlando",
        "Prizm",
        "Rezzo",
        "S-10 Pickup",
        "Sail",
        "Silverado",
        "Sonic",
        "Spark",
        "Special DeLuxe",
        "Spin",
        "SS",
        "SSR",
        "Starcraft",
        "Suburban",
        "Tacuma",
        "Tahoe",
        "Tavera",
        "Tracker",
        "TrailBlazer",
        "Trans Sport",
        "Traverse",
        "Trax",
        "Uplander",
        "Van",
        "Vectra",
        "Venture",
        "Viva",
        "Volt",
        "Zafira"
    ],
    "Citroen": [
        "2 CV",
        "AMI",
        "AX",
        "Berlingo",
        "BX",
        "C-Crosser",
        "C-Elysee",
        "C-Quatre",
        "C-Triomphe",
        "C-ZERO",
        "C1",
        "C2",
        "C3",
        "C3 Aircross",
        "C3 Picasso",
        "C4",
        "C4 Aircross",
        "C4 Cactus",
        "C4 Picasso",
        "C4 SpaceTourer",
        "C5",
        "C5 Aircross",
        "C5 X",
        "C6",
        "C8",
        "CX",
        "DS",
        "DS3",
        "DS4",
        "DS5",
        "Dyane",
        "E-Mehari",
        "Evasion",
        "GS",
        "Jumpy",
        "LN",
        "Nemo",
        "Saxo",
        "SM",
        "SpaceTourer",
        "Traction Avant",
        "Visa",
        "Xantia",
        "XM",
        "Xsara",
        "Xsara Picasso",
        "ZX"
    ],
    "Ferrari": [
        "250 GTO",
        "296",
        "328",
        "348",
        "360",
        "400",
        "412",
        "456",
        "458",
        "488",
        "512 BB",
        "512 M",
        "512 TR",
        "550",
        "575M",
        "599",
        "612",
        "812",
        "California",
        "Daytona SP3",
        "Dino 206 GT",
        "Dino 208/308 GT4",
        "Dino 246 GT",
        "Enzo",
        "F12berlinetta",
        "F355",
        "F40",
        "F430",
        "F50",
        "F8",
        "FF",
        "FXX K",
        "GTC4Lusso",
        "LaFerrari",
        "Mondial",
        "Monza SP",
        "Portofino",
        "Roma",
        "SF90 Stradale",
        "Testarossa"
    ],
    "Tesla": [
        "Model S",
        "Model 3",
        "Model X",
        "Model Y",
        "Cybertruck",
        "Roadster"
    ],
    "Ford": [
        "Aerostar",
        "Aspire",
        "B-MAX",
        "Bronco",
        "Bronco Sport",
        "Bronco-II",
        "C-MAX",
        "Capri",
        "Consul",
        "Contour",
        "Cortina",
        "Cougar",
        "Country Squire",
        "Crown Victoria",
        "Custom",
        "Econoline",
        "Econovan",
        "EcoSport",
        "Edge",
        "Escape",
        "Escort",
        "Escort (North America)",
        "Everest",
        "Excursion",
        "Expedition",
        "Explorer",
        "Explorer Sport Trac",
        "F-150",
        "F-2",
        "Fairlane",
        "Fairmont",
        "Falcon",
        "Festiva",
        "Fiesta",
        "Fiesta ST",
        "Five Hundred",
        "Flex",
        "Focus",
        "Focus RS",
        "Focus ST",
        "Freda",
        "Freestar",
        "Freestyle",
        "Fusion",
        "Fusion (North America)",
        "Galaxie",
        "Galaxy",
        "GPA",
        "Granada",
        "Granada (North America)",
        "GT",
        "GT40",
        "Ikon",
        "Ixion",
        "KA",
        "Kuga",
        "Laser",
        "LTD Country Squire",
        "LTD Crown Victoria",
        "M151",
        "Mainline",
        "Maverick",
        "Model A",
        "Model T",
        "Mondeo",
        "Mondeo ST",
        "Mustang",
        "Mustang Mach-E",
        "Orion",
        "Probe",
        "Puma",
        "Puma ST",
        "Ranchero",
        "Ranger",
        "Ranger (North America)",
        "S-MAX",
        "Scorpio",
        "Sierra",
        "Spectron",
        "Taunus",
        "Taurus",
        "Taurus X",
        "Telstar",
        "Tempo",
        "Territory",
        "Thunderbird",
        "Torino",
        "Tourneo Connect",
        "Tourneo Courier",
        "Tourneo Custom",
        "Transit Connect",
        "V8",
        "Windstar",
        "Zephyr"
    ],
    "Honda": [
        "145",
        "Accord",
        "Acty",
        "Airwave",
        "Ascot",
        "Ascot Innova",
        "Avancier",
        "Ballade",
        "Beat",
        "Brio",
        "Capa",
        "City",
        "Civic",
        "Civic Ferio",
        "Civic Type R",
        "Clarity",
        "Concerto",
        "CR-V",
        "CR-X",
        "CR-Z",
        "Crossroad",
        "Crosstour",
        "Domani",
        "e",
        "Edix",
        "Element",
        "Elysion",
        "Fit",
        "Fit Aria",
        "Fit Shuttle",
        "FR-V",
        "Freed",
        "Grace",
        "Horizon",
        "HR-V",
        "Insight",
        "Inspire",
        "Integra",
        "Integra SJ",
        "Jade",
        "Jazz",
        "Lagreat",
        "Legend",
        "Life",
        "Logo",
        "MDX",
        "Mobilio",
        "Mobilio Spike",
        "N-BOX",
        "N-BOX Slash",
        "N-One",
        "N-WGN",
        "N360",
        "NSX",
        "Odyssey",
        "Odyssey (North America)",
        "Orthia",
        "Partner",
        "Passport",
        "Pilot",
        "Prelude",
        "Quint",
        "Rafaga",
        "Ridgeline",
        "S-MX",
        "S2000",
        "S500",
        "S600",
        "S660",
        "Saber",
        "Shuttle",
        "Stepwgn",
        "Stream",
        "Street",
        "That'S",
        "Today",
        "Torneo",
        "Vamos",
        "Vezel",
        "Vigor",
        "Z",
        "Zest"
    ],
    "Hyundai": [
        "Accent",
        "Aslan",
        "Atos",
        "Avante",
        "Avante N",
        "Azera",
        "Bayon",
        "Centennial",
        "Click",
        "Coupe",
        "Creta",
        "Dynasty",
        "Elantra",
        "Elantra N",
        "Encino",
        "Entourage",
        "EON",
        "Equus",
        "Excel",
        "Galloper",
        "Genesis",
        "Genesis Coupe",
        "Getz",
        "Grace",
        "Grand Starex",
        "Grandeur",
        "H-1",
        "H200",
        "HB20",
        "i10",
        "i20",
        "i20 N",
        "i30",
        "i30 N",
        "i40",
        "IONIQ",
        "IONIQ 5",
        "ix20",
        "ix35",
        "ix55",
        "Kona",
        "Lantra",
        "Lavita",
        "Marcia",
        "Matrix",
        "Maxcruz",
        "Palisade",
        "Pony",
        "Santa Cruz",
        "Santa Fe",
        "Santamo",
        "Scoupe",
        "Solaris",
        "Sonata",
        "Starex",
        "Staria",
        "Stellar",
        "Terracan",
        "Tiburon",
        "Trajet",
        "Tucson",
        "Tuscani",
        "Veloster",
        "Venue",
        "Veracruz",
        "Verna",
        "XG"
    ],
    "Kia": [
        "Avella",
        "Borrego",
        "Cadenza",
        "Capital",
        "Carens",
        "Carnival",
        "Carstar",
        "Ceed",
        "Ceed GT",
        "Cerato",
        "Clarus",
        "Concord",
        "Elan",
        "Enterprise",
        "EV6",
        "Forte",
        "Joice",
        "K3",
        "K5",
        "K7",
        "K8",
        "K9",
        "K900",
        "Lotze",
        "Magentis",
        "Mentor",
        "Mohave",
        "Morning",
        "Niro",
        "Opirus",
        "Optima",
        "Picanto",
        "Potentia",
        "Pregio",
        "Pride",
        "Proceed",
        "Quanlima",
        "Quoris",
        "Ray",
        "Retona",
        "Rio",
        "Sedona",
        "Seltos",
        "Sephia",
        "Shuma",
        "Sorento",
        "Soul",
        "Soul EV",
        "Spectra",
        "Sportage",
        "Stinger",
        "Stonic",
        "Telluride",
        "Towner",
        "Venga",
        "Visto",
        "X-Trek",
        "XCeed"
    ],
    "LADA (ВАЗ)": [
        "1111 Ока",
        "2101",
        "2102",
        "2103",
        "2104",
        "2105",
        "2106",
        "2107",
        "2108",
        "2109",
        "21099",
        "2110",
        "2111",
        "2112",
        "2113",
        "2114",
        "2115",
        "2120 Надежда",
        "2121 (4x4)",
        "2123",
        "2129",
        "2131 (4x4)",
        "2328",
        "2329",
        "EL Lada",
        "Granta",
        "Kalina",
        "Largus",
        "Niva",
        "Niva Legend",
        "Priora",
        "Revolution",
        "Vesta",
        "XRAY"
    ],
    "Lamborghini": [
        "350/400 GT",
        "Aventador",
        "Centenario",
        "Countach",
        "Countach LPI 800-4",
        "Diablo",
        "Egoista",
        "Espada",
        "Gallardo",
        "Huracán",
        "Islero",
        "Jalpa",
        "Jarama",
        "LM001",
        "LM002",
        "Miura",
        "Murcielago",
        "Reventon",
        "Sesto Elemento",
        "Silhouette",
        "Sián",
        "Urraco",
        "Urus",
        "Veneno"
    ],
}

colors = [
    'Red',
    'Grey',
    'Light blue',
    'Dark blue',
    'Green',
    'Yellow',
    'Pink',
    'Orange',
    'Brown',
    'White',
    'Black',
    'Violet',
]

body_types = [
    'SUV',
    'Sedan',
    'Сoupe',
    'Wagon',
    'Minivan',
    'Hatchback',
    'Liftback',
    'Limousine',
    'Cabriolet',
    'Another'
]

transmission = ['Automatic', 'Manual']

fuel = [
    'Petrol',
    'Diesel',
    'Gas',
    'Electric',
    'Hybrid'
]

countries = [
    "US",
    "RU",
    "DE",
    "BY",
    "IT",

]

customer_list = [
    'Kirill Rachalovsky',
    'Anton Tester',
    'Sasha Businessman',
    'Harry Potter',
    'Ron Weasley',
    'Hermione Granger',
    'Sponge Bob',
    'Patric Star',
    'Daniel Clarke'
]

showroom_list =[
    "Av.by",
    "Auto.ru",
    "Atlant.by",
    "Avito.ru",
]

def get_random_color():
    return random.choice(colors)


def get_random_body_type():
    return random.choice(body_types)


def get_random_fuel():
    return random.choice(fuel)


def get_random_country():
    return random.choice(countries)


def get_random_transmission():
    return random.choice(transmission)


def get_random_year():
    return random.randint(1980, 2022)


def default_showroom_priorities():
    return {"brand": "Tesla",
            "car_model": "Model S",
            "color": "Black",
            "transmission": "Automatic",
            "fuel": "Electric",
            "year": "2020",
            "body_type": "Sedan"}


def get_random_car():
    brand = str(random.choice(list(cars_models.keys())))
    car_model = str(random.choice(list(cars_models[brand])))
    return {"brand": brand, "car_model": car_model}