# Generated by Django 4.1 on 2022-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(default=1000000, help_text='<i>Put your balance in dollars</i>', verbose_name='Balance'),
        ),
    ]
