# Generated by Django 4.0.6 on 2022-07-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(default=500000, help_text='<i>Put your balance in dollars</i>', verbose_name='Balance'),
        ),
    ]
