# Generated by Django 4.1 on 2022-08-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_deals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
