# Generated by Django 4.0.6 on 2022-07-29 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealerdiscount',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 8, 28)),
        ),
    ]
