# Generated by Django 4.0.6 on 2022-08-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms_cars', to='showroom.showroom'),
        ),
    ]
