# Generated by Django 4.0.6 on 2022-08-10 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdiscountscars',
            name='data_end',
            field=models.DateField(default=datetime.date(2022, 9, 9)),
        ),
        migrations.AlterField(
            model_name='dealerdiscountscars',
            name='data_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
